<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../XamlG.ProjectSystem/XamlG.ProjectSystem.csproj" />
    <ProjectReference Include="../XamlG.Tooling/XamlG.Tooling.csproj" />
    <ProjectReference Include="../XamlG.Frameworks/XamlG.Frameworks.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="Microsoft.Build.Locator" />
  </ItemGroup>
</Project>
