<Project>
  <PropertyGroup>
    <XamlGEnabled Condition="'$(XamlGEnabled)' == ''">true</XamlGEnabled>
    <XamlGFramework Condition="'$(XamlGFramework)' == ''">Auto</XamlGFramework>
    <XamlGEnableDefaultItems Condition="'$(XamlGEnableDefaultItems)' == ''">true</XamlGEnableDefaultItems>
    <XamlGGenerateInitializeComponent Condition="'$(XamlGGenerateInitializeComponent)' == ''">true</XamlGGenerateInitializeComponent>
    <XamlGGenerateNamedFields Condition="'$(XamlGGenerateNamedFields)' == ''">true</XamlGGenerateNamedFields>
    <EnableAvaloniaXamlCompilation Condition="'$(XamlGEnabled)' == 'true'">false</EnableAvaloniaXamlCompilation>
    <AvaloniaNameGeneratorIsEnabled Condition="'$(XamlGEnabled)' == 'true'">false</AvaloniaNameGeneratorIsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="XamlGEnabled;XamlGFramework;XamlGGenerateInitializeComponent;XamlGGenerateNamedFields;MSBuildProjectDirectory" />
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="XamlGCompile" />
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="XamlGLogicalPath" />
  </ItemGroup>
</Project>
