import test from 'node:test';
import assert from 'node:assert/strict';
import { request as httpRequest } from 'node:http';
import { createHash } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { GitHubClient, CompanionClient, boundedText } from '../../tools/XamlG.Playground/wwwroot/git/github.mjs';
import { OAuthBroker } from '../../tools/git-companion/oauth.mjs';
import { startCompanion } from '../../tools/git-companion/server.mjs';
const response = (value, status = 200, headers = {}) => new Response(JSON.stringify(value), { status, headers });
function broker(overrides = {}) { return new OAuthBroker({ clientId: 'test-client', clientSecret: 'server-test-secret', redirectUri: 'http://127.0.0.1:47831/oauth/callback', fetcher: async () => response({ access_token: 'oauth-test-token', token_type: 'bearer' }), onToken: async () => ({ login: 'owner' }), ...overrides }); }
test('OAuth uses state, S256 PKCE and a server-side code exchange', async () => { let exchange, token; const oauth = broker({ fetcher: async (url, options) => { exchange = { url, options }; return response({ access_token: 'oauth-test-token' }); }, onToken: async value => { token = value; return { login: 'owner' }; } }); const session = oauth.begin('https://studio.test'), url = new URL(session.authorizeUrl); assert.equal(url.searchParams.get('code_challenge_method'), 'S256'); assert.equal(url.searchParams.has('client_secret'), false); await oauth.callback(url.searchParams.get('state'), 'code'); const params = exchange.options.body; assert.equal(createHash('sha256').update(params.get('code_verifier')).digest('base64url'), url.searchParams.get('code_challenge')); assert.equal(params.get('client_secret'), 'server-test-secret'); assert.equal(token, 'oauth-test-token'); const status = oauth.status(session.handle, 'https://studio.test'); assert.equal(status.status, 'authorized'); assert.doesNotMatch(JSON.stringify(status), /oauth-test-token|server-test-secret/); });
test('OAuth state is single-use and status handles are origin-bound', async () => { const oauth = broker(), session = oauth.begin('https://studio.test'), state = new URL(session.authorizeUrl).searchParams.get('state'); assert.throws(() => oauth.status(session.handle, 'https://evil.test'), { code: 'oauth_session' }); await oauth.callback(state, 'code'); await assert.rejects(oauth.callback(state, 'code'), { code: 'oauth_state' }); });
test('OAuth expiration and cancellation fail closed', async () => { let now = 1000; const oauth = broker({ clock: () => now }); let session = oauth.begin('https://studio.test'), state = new URL(session.authorizeUrl).searchParams.get('state'); now += 600001; await assert.rejects(oauth.callback(state, 'code'), { code: 'oauth_state' }); session = oauth.begin('https://studio.test'); state = new URL(session.authorizeUrl).searchParams.get('state'); oauth.cancel(session.handle, 'https://studio.test'); await assert.rejects(oauth.callback(state, 'code'), { code: 'oauth_state' }); });
test('sign-out during OAuth exchange cannot install credentials', async () => { let resolve, installed = false; const oauth = broker({ fetcher: () => new Promise(r => resolve = r), onToken: async () => { installed = true; } }); const session = oauth.begin('https://studio.test'), state = new URL(session.authorizeUrl).searchParams.get('state'), pending = oauth.callback(state, 'code'); oauth.clear(); resolve(response({ access_token: 'oauth-test-token' })); await assert.rejects(pending, { code: 'oauth_canceled' }); assert.equal(installed, false); });
test('companion requires exact Origin, Host, owner credential and JSON content type', async t => { const root = await mkdtemp(join(tmpdir(), 'xamlg-http-')); const server = await startCompanion({ root, origins: ['https://studio.test'], port: 0 }); t.after(async () => { await server.close(); await rm(root, { recursive: true, force: true }); }); const call = (headers, body = '{}') => fetch(server.address + '/health', { method: 'POST', headers: { Origin: 'https://studio.test', 'Content-Type': 'application/json', ...headers }, body }); assert.equal((await call({})).status, 401); assert.equal((await call({ Authorization: `Bearer ${server.token}`, Origin: 'https://evil.test' })).status, 403); const badHost = await new Promise((resolve, reject) => { const req = httpRequest(server.address + '/health', { method: 'POST', headers: { Host: 'evil.test', Origin: 'https://studio.test', Authorization: `Bearer ${server.token}`, 'Content-Type': 'application/json' } }, response => { response.resume(); response.on('end', () => resolve(response.statusCode)); }); req.on('error', reject); req.end('{}'); }); assert.equal(badHost, 403); assert.equal((await call({ Authorization: `Bearer ${server.token}`, 'Content-Type': 'text/plain' })).status, 400); const good = await call({ Authorization: `Bearer ${server.token}` }); assert.equal(good.status, 200); assert.equal(good.headers.get('access-control-allow-origin'), 'https://studio.test'); assert.equal((await good.json()).version, 1); });
test('authenticated companion exposes native repositories and safe CORS preflight', async t => { const root = await mkdtemp(join(tmpdir(), 'xamlg-http-')); const service = await startCompanion({ root, origins: ['https://studio.test'], port: 0 }); t.after(async () => { await service.close(); await rm(root, { recursive: true, force: true }); }); const client = new CompanionClient(service.address, service.token, (url, options) => fetch(url, { ...options, headers: { ...options.headers, Origin: 'https://studio.test' } })); const repo = await client.call('git/init', { name: 'test' }); assert.equal((await client.call('git/list')).length, 1); assert.equal((await client.call('git/run', { id: repo.id, operation: 'status' })).head, null); const preflight = await fetch(service.address + '/git/run', { method: 'OPTIONS', headers: { Origin: 'https://studio.test', 'Access-Control-Request-Method': 'POST', 'Access-Control-Request-Headers': 'authorization,content-type' } }); assert.equal(preflight.status, 204); assert.equal(preflight.headers.get('access-control-allow-origin'), 'https://studio.test'); });
