import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { repositoryPath, branchName, githubRemote, gitHash, buildTrees, makeCommit, utf8, text, SerialQueue, base64, unbase64 } from '../../tools/XamlG.Playground/wwwroot/git/core.mjs';
import { diffLines, diffHunks, applyHunks, unifiedDiff } from '../../tools/XamlG.Playground/wwwroot/git/diff.mjs';

for (const path of ['../x', '/x', 'a//b', 'a/./b', 'a/../b', '.git/config', 'x/.GIT/hooks/post-checkout', 'a\\b', 'C:/x', 'x\0y', 'x.']) test(`reject path ${JSON.stringify(path)}`, () => assert.throws(() => repositoryPath(path)));
for (const name of ['-main', 'a..b', '@', 'a@{b', 'a.lock', 'a/.b', 'a b', 'a~b', 'a/', '/a']) test(`reject ref ${name}`, () => assert.throws(() => branchName(name)));
test('allows real repository paths, prototype keys and branch slashes', () => { assert.equal(repositoryPath('źródła/__proto__/file.cs'), 'źródła/__proto__/file.cs'); assert.equal(branchName('feature/git-workspaces'), 'feature/git-workspaces'); });
test('HTTPS URL authentication and origin validation', () => { assert.equal(githubRemote('https://github.com/owner/repo.git').repo, 'repo'); for (const url of ['http://github.com/a/b', 'https://x:y@github.com/a/b', 'https://github.com.evil/a/b', 'https://github.com/a/b?token=x', 'https://github.com/a/b#x', 'https://github.com/a%2fb/c']) assert.throws(() => githubRemote(url)); });
test('blob hashes match native Git for text, binary and Unicode', async () => { for (const bytes of [utf8('hello\n'), Uint8Array.of(0, 255, 127, 1), utf8('Zażółć gęślą jaźń')]) { const expected = execFileSync('git', ['hash-object', '--stdin'], { input: bytes }).toString().trim(); assert.equal(await gitHash('blob', bytes), expected); assert.deepEqual(unbase64(base64(bytes)), bytes); } });
test('canonical tree hashes match native Git serialization', async () => { const files = new Map(); for (const path of ['a.c', 'a/empty', 'a0', 'ą']) files.set(path, { oid: await gitHash('blob', utf8(path)), mode: path === 'a0' ? '100755' : '100644' }); const trees = await buildTrees(files); for (const tree of trees.objects) assert.equal(tree.oid, execFileSync('git', ['hash-object', '-t', 'tree', '--stdin'], { input: tree.bytes }).toString().trim()); assert.equal(trees.objects.at(-1).entries.map(x => x.name).join(','), 'a.c,a,a0,ą'); });
test('tree builder rejects directory/file collisions', async () => { const id = '1'.repeat(40); await assert.rejects(buildTrees(new Map([['a', { oid: id, mode: '100644' }], ['a/b', { oid: id, mode: '100644' }]])), { code: 'path_collision' }); });
test('commit hashes match native Git and enforce identity', async () => { const tree = (await buildTrees(new Map())).oid; const commit = await makeCommit(tree, [], 'A message', { name: 'Test', email: 'test@example.com', date: '2026-01-01T00:00:00.123Z' }); assert.equal(commit.oid, execFileSync('git', ['hash-object', '-t', 'commit', '--stdin'], { input: commit.bytes }).toString().trim()); assert.equal(commit.author.date, '2026-01-01T00:00:00.000Z'); await assert.rejects(makeCommit(tree, [], 'x', { name: 'x\ncommitter y', email: 'x@y.z' })); });
test('serial queue recovers after rejected mutations', async () => { const q = new SerialQueue(), events = []; await assert.rejects(q.run(async () => { events.push(1); throw new Error(); })); await q.run(() => events.push(2)); assert.deepEqual(events, [1, 2]); });
test('Myers round trips randomized line changes without losing line endings', () => { let seed = 7123; const rand = n => { seed = (seed * 1664525 + 1013904223) >>> 0; return seed % n; }; for (let i = 0; i < 1000; i++) { const generate = () => Array.from({ length: rand(20) }, () => ['a\n', 'b\r\n', 'c\n', '\n'][rand(4)]).join('') + (rand(2) ? 'tail' : ''); const a = generate(), b = generate(), diff = diffLines(a, b); assert.equal(diff.edits.filter(x => x.type !== 'add').map(x => x.line).join(''), a); assert.equal(diff.edits.filter(x => x.type !== 'delete').map(x => x.line).join(''), b); const { hunks } = diffHunks(a, b); assert.equal(applyHunks(a, hunks, hunks.map(h => h.id)), b); } });
test('diff work limit falls back to exact replacement', () => { const result = diffLines('a\n'.repeat(100), 'b\n'.repeat(100), 1); assert.equal(result.bounded, true); assert.equal(result.edits.filter(x => x.type !== 'delete').map(x => x.line).join(''), 'b\n'.repeat(100)); });
test('partial hunk staging preserves unrelated changes', () => { const a = Array.from({ length: 30 }, (_, i) => `${i}\n`).join(''), b = a.replace('1\n', 'one\n').replace('28\n', 'twenty-eight\n'); const { hunks } = diffHunks(a, b); assert.equal(hunks.length, 2); assert.equal(applyHunks(a, hunks, [0]), a.replace('1\n', 'one\n')); assert.throws(() => applyHunks('bad', hunks, [0]), { code: 'stale_hunk' }); });
test('unified diff retains missing newline markers', () => { const { patch } = unifiedDiff('a', 'old', 'new'); assert.match(patch, /No newline at end of file/); assert.match(patch, /-old/); assert.match(patch, /\+new/); });

test('UTF-8 decoding preserves BOM, mixed EOLs and missing final newline', () => { const source = '\uFEFFfirst\r\nsecond\nlast'; assert.equal(text(utf8(source)), source); });
