import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile, rm, mkdir, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync, spawn } from 'node:child_process';
import { createServer } from 'node:https';
import { NativeGit, parseStatus } from '../../tools/git-companion/native.mjs';
const identity = { name: 'Test Author', email: 'test@example.com' };
async function fixture(t) { const root = await mkdtemp(join(tmpdir(), 'xamlg-native-')); t.after(() => rm(root, { recursive: true, force: true })); const git = new NativeGit(root), repo = await git.init(); const run = (op, args) => git.execute(repo.id, op, args); return { root, git, repo, run, path: join(root, 'repos', repo.id, 'worktree') }; }
async function write(run, path, content, expectedVersion = null) { return run('write', { path, base64: Buffer.from(content).toString('base64'), expectedVersion }); }
async function commit(run, message = 'change') { await run('stage', { paths: await run('files') }); return (await run('commit', { ...identity, message })).head; }
test('porcelain parser preserves spaces/newlines and rename origins', () => { assert.deepEqual(parseStatus('R  new name\0old name\0?? a\nb\0UU conflict\0').map(x => [x.code, x.path, x.original, x.conflict]), [['R ', 'new name', 'old name', false], ['??', 'a\nb', null, false], ['UU', 'conflict', null, true]]); });
test('native init/edit/index/commit/diff/log/branch workflow', async t => { const { run } = await fixture(t); assert.equal((await run('status')).head, null); await write(run, 'src/view.axaml', 'one\n'); await run('stage', { paths: ['src/view.axaml'] }); const version = (await run('read', { path: 'src/view.axaml' })).version; await write(run, 'src/view.axaml', 'two\n', version); const first = await run('commit', { ...identity, message: 'first' }); assert.match((await run('diff', { path: 'src/view.axaml' })).patch, /\+two/); assert.equal((await run('status')).entries[0].code, ' M'); await run('discard', { paths: ['src/view.axaml'], confirm: 'discard' }); await run('branch', { branch: 'feature/x' }); await run('checkout', { branch: 'feature/x' }); const refs = await run('branches'); assert.equal(refs.find(r => r.current).name, 'refs/heads/feature/x'); const history = await run('log'); assert.equal(history[0].oid, first.head); assert.deepEqual(history[0].parents, []); assert.equal(history[0].author.name, identity.name); });
test('native stale file checks and binary round trip', async t => { const { run } = await fixture(t), bytes = Uint8Array.of(0, 255, 1, 128); await write(run, 'binary', bytes); const first = await run('read', { path: 'binary' }); assert.deepEqual(Buffer.from(first.base64, 'base64'), Buffer.from(bytes)); await write(run, 'binary', 'new', first.version); await assert.rejects(write(run, 'binary', 'lost', first.version), { code: 'stale_file' }); });
test('native paths and symlinks cannot escape the managed worktree', async t => { const { root, run, path } = await fixture(t); for (const name of ['../outside', '.git/config', '/tmp/a', 'x/.git/config']) await assert.rejects(write(run, name, 'bad')); const target = join(root, 'target'); await writeFile(target, 'safe'); await symlink(target, join(path, 'link')); await assert.rejects(run('read', { path: 'link' }), { code: 'unsafe_path' }); await assert.rejects(write(run, 'link', 'unsafe'), { code: 'unsafe_path' }); await mkdir(join(root, 'outside')); await symlink(join(root, 'outside'), join(path, 'directory')); await assert.rejects(write(run, 'directory/evil', 'unsafe'), { code: 'unsafe_path' }); assert.equal(await readFile(target, 'utf8'), 'safe'); });
test('native Git hooks are disabled even in an owned repository', async t => { const { run, path } = await fixture(t); await mkdir(join(path, '.git', 'hooks'), { recursive: true }); await writeFile(join(path, '.git', 'hooks', 'pre-commit'), '#!/bin/sh\nexit 42\n', { mode: 0o755 }); await write(run, 'a', 'a'); await commit(run); assert.ok((await run('status')).head); });
test('native unstage works on unborn branch and preserves files', async t => { const { run } = await fixture(t); await write(run, 'a', 'a'); await run('stage', { paths: ['a'] }); await run('unstage', { paths: ['a'] }); assert.equal((await run('status')).entries[0].code, '??'); assert.equal(Buffer.from((await run('read', { path: 'a' })).base64, 'base64').toString(), 'a'); });
test('native stash restores tracked and untracked files', async t => { const { run } = await fixture(t); await write(run, 'a', 'base'); await commit(run); const old = await run('read', { path: 'a' }); await write(run, 'a', 'next', old.version); await write(run, 'untracked', 'new'); await run('stash', { message: 'draft' }); assert.equal((await run('status')).entries.length, 0); assert.match((await run('stashes')).text, /draft/); await run('popstash', { index: 0 }); assert.equal((await run('status')).entries.length, 2); });
test('native conflict, resolution and merge continuation', async t => { const { run } = await fixture(t); await write(run, 'a', 'base\n'); await commit(run, 'base'); await run('branch', { branch: 'other' }); let file = await run('read', { path: 'a' }); await write(run, 'a', 'ours\n', file.version); await commit(run, 'ours'); await run('checkout', { branch: 'other' }); file = await run('read', { path: 'a' }); await write(run, 'a', 'theirs\n', file.version); const theirs = await commit(run, 'theirs'); await run('checkout', { branch: 'main' }); await assert.rejects(run('merge', { commit: theirs }), { code: 'git_failed' }); assert.ok((await run('status')).operation.includes('MERGE_HEAD')); file = await run('read', { path: 'a' }); await write(run, 'a', 'resolved\n', file.version); await run('stage', { paths: ['a'] }); await run('continue', { operation: 'merge' }); assert.equal((await run('log'))[0].parents.length, 2); });
test('native arbitrary commands, transports and destructive operations are rejected', async t => { const { git, run } = await fixture(t); await assert.rejects(git.clone({ url: 'file:///tmp/repo' }), { code: 'invalid_remote' }); await assert.rejects(git.clone({ url: 'https://evil.example/repo' }), { code: 'invalid_remote' }); await assert.rejects(run('shell', { command: 'echo bad' }), { code: 'unsupported_operation' }); await assert.rejects(run('discard', { paths: ['a'] }), { code: 'confirmation_required' }); await assert.rejects(run('branch', { branch: '--config=bad' }), { code: 'invalid_ref' }); });
test('native smart HTTPS authenticated clone, fetch, fast-forward pull and push', async t => {
    const root = await mkdtemp(join(tmpdir(), 'xamlg-https-')); t.after(() => rm(root, { recursive: true, force: true }));
    const bare = join(root, 'remote.git'), seed = join(root, 'seed'), key = join(root, 'key.pem'), cert = join(root, 'cert.pem');
    const gitCmd = (args, cwd) => execFileSync('git', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim();
    execFileSync('openssl', ['req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-keyout', key, '-out', cert, '-days', '1', '-subj', '/CN=localhost', '-addext', 'subjectAltName=DNS:localhost'], { stdio: 'ignore' });
    gitCmd(['init', '--bare', '--initial-branch=main', bare]); gitCmd(['config', 'http.receivepack', 'true'], bare); gitCmd(['clone', bare, seed]); gitCmd(['config', 'user.name', 'Test'], seed); gitCmd(['config', 'user.email', 'test@example.com'], seed); await writeFile(join(seed, 'a'), 'initial\n'); gitCmd(['add', '.'], seed); gitCmd(['commit', '-m', 'initial'], seed); gitCmd(['push', 'origin', 'main'], seed);
    const credential = 'Basic ' + Buffer.from('test:test-password').toString('base64'); let authorizedRequests = 0;
    const server = createServer({ key: await readFile(key), cert: await readFile(cert) }, async (req, res) => {
        if (req.headers.authorization !== credential) { res.writeHead(401, { 'WWW-Authenticate': 'Basic realm="Git test"' }); res.end(); return; }
        authorizedRequests++; const url = new URL(req.url, 'https://localhost'), chunks = []; for await (const chunk of req) chunks.push(chunk);
        const backend = spawn('git', ['http-backend'], { env: { ...process.env, GIT_PROJECT_ROOT: root, GIT_HTTP_EXPORT_ALL: '1', PATH_INFO: url.pathname, QUERY_STRING: url.search.slice(1), REQUEST_METHOD: req.method, CONTENT_TYPE: req.headers['content-type'] ?? '', CONTENT_LENGTH: String(Buffer.concat(chunks).length), REMOTE_USER: 'test', SERVER_PROTOCOL: 'HTTP/1.1' }, stdio: ['pipe', 'pipe', 'pipe'] });
        const output = []; backend.stdout.on('data', c => output.push(c)); backend.stderr.resume(); backend.stdin.end(Buffer.concat(chunks));
        backend.on('close', () => { const bytes = Buffer.concat(output), split = bytes.indexOf('\r\n\r\n'); if (split < 0) { res.writeHead(500); res.end(); return; } let status = 200; const headers = {}; for (const line of bytes.subarray(0, split).toString().split('\r\n')) { const colon = line.indexOf(':'); if (colon < 0) continue; const name = line.slice(0, colon), value = line.slice(colon + 1).trim(); if (name.toLowerCase() === 'status') status = parseInt(value); else headers[name] = value; } res.writeHead(status, headers); res.end(bytes.subarray(split + 4)); });
    });
    await new Promise(r => server.listen(0, '127.0.0.1', r)); t.after(() => new Promise(r => server.close(r))); const origin = `https://localhost:${server.address().port}`, native = new NativeGit(join(root, 'managed'), { hosts: ['localhost'], caFile: cert });
    native.setCredential(origin, 'test', 'test-password'); const repo = await native.clone({ url: `${origin}/remote.git` }), run = (op, args) => native.execute(repo.id, op, args);
    assert.equal(Buffer.from((await run('read', { path: 'a' })).base64, 'base64').toString(), 'initial\n');
    await writeFile(join(seed, 'a'), 'upstream\n'); gitCmd(['commit', '-am', 'upstream'], seed); gitCmd(['push', 'origin', 'main'], seed);
    await run('fetch'); await run('pull', { branch: 'main' }); const current = await run('read', { path: 'a' }); assert.equal(Buffer.from(current.base64, 'base64').toString(), 'upstream\n');
    await write(run, 'a', 'published\n', current.version); const head = await commit(run, 'published'); await run('push', { branch: 'main', confirm: 'push' }); assert.equal(gitCmd(['rev-parse', 'refs/heads/main'], bare), head);
    const config = await readFile(join(root, 'managed', 'repos', repo.id, 'worktree', '.git', 'config'), 'utf8'); assert.doesNotMatch(config, /test-password|Authorization|extraHeader/); assert.ok(authorizedRequests >= 4);
});

test('literal pathspec staging does not accidentally stage wildcard matches', async t => { const { run } = await fixture(t); await write(run, 'a[1].txt', 'literal'); await write(run, 'a1.txt', 'other'); await run('stage', { paths: ['a[1].txt'] }); const status = await run('status'); assert.equal(status.entries.find(e => e.path === 'a[1].txt').code, 'A '); assert.equal(status.entries.find(e => e.path === 'a1.txt').code, '??'); });

test('native diff shows untracked text and discard deletes only confirmed files', async t => {
    const { run } = await fixture(t); await write(run, 'new.txt', 'untracked content\n');
    assert.match((await run('diff', { path: 'new.txt' })).patch, /\+untracked content/);
    await assert.rejects(run('discard', { paths: ['new.txt'] }), { code: 'confirmation_required' });
    await run('discard', { paths: ['new.txt'], confirm: 'discard' });
    assert.deepEqual(await run('files'), []);
});
test('native writes reject noncanonical base64 before changing a file', async t => {
    const { run } = await fixture(t);
    await assert.rejects(run('write', { path: 'bad', base64: 'not base64!', expectedVersion: null }), { code: 'invalid_base64' });
    assert.deepEqual(await run('files'), []);
});
