import test from 'node:test';
import assert from 'node:assert/strict';
import { VirtualRepository } from '../../tools/XamlG.Playground/wwwroot/git/virtual.mjs';
import { MemoryWorkspaceStore } from '../../tools/XamlG.Playground/wwwroot/git/storage.mjs';
import { text } from '../../tools/XamlG.Playground/wwwroot/git/core.mjs';
import { FakeGitHub } from './fake-github.mjs';
const author = { name: 'Test', email: 'test@example.com', date: '2026-01-02T00:00:00Z' };
async function fixture(files = { 'view.axaml': 'original\n', 'nested/file.cs': 'class A {}\n' }) { const store = new MemoryWorkspaceStore(), api = new FakeGitHub(); await api.seed(files); const repo = await VirtualRepository.clone(store, api, 'https://github.com/owner/repo'); return { repo, api, store }; }
const read = async (repo, path, area) => text((await repo.read(path, area)).bytes);
test('clone validates trees and loads blobs lazily', async () => { const { repo, api } = await fixture(); assert.equal(repo.state.worktree.size, 2); assert.equal(api.calls.filter(c => c.path.includes('/git/blobs/')).length, 0); assert.equal(await read(repo, 'view.axaml'), 'original\n'); assert.equal(api.calls.filter(c => c.path.includes('/git/blobs/')).length, 1); await read(repo, 'view.axaml'); assert.equal(api.calls.filter(c => c.path.includes('/git/blobs/')).length, 1); });
test('truncated recursive trees fall back to directory traversal', async () => { const api = new FakeGitHub(), store = new MemoryWorkspaceStore(); await api.seed({ 'a/b/c': 'c', x: 'x' }); api.forceTruncated = true; const repo = await VirtualRepository.clone(store, api, 'https://github.com/owner/repo'); assert.equal(repo.state.worktree.size, 2); assert.equal(await read(repo, 'a/b/c'), 'c'); });
test('HEAD, index and worktree are independent and commit uses only index', async () => { const { repo } = await fixture(); await repo.write('view.axaml', 'staged'); await repo.stage(['view.axaml']); await repo.write('view.axaml', 'unstaged'); const id = await repo.commit('first', author); assert.equal(repo.status().head, id); assert.equal(await read(repo, 'view.axaml', 'head'), 'staged'); assert.equal(await read(repo, 'view.axaml', 'index'), 'staged'); assert.equal(await read(repo, 'view.axaml'), 'unstaged'); assert.equal(repo.status().staged.length, 0); assert.equal(repo.status().unstaged.length, 1); });
test('persistent reload preserves local commits and blobs', async () => { const { repo, api, store } = await fixture(); await repo.write('new.cs', 'new'); await repo.stage(['new.cs']); const id = await repo.commit('new file', author); const reopened = await VirtualRepository.load(store, api, repo.state.id); assert.equal(reopened.status().head, id); assert.equal(await read(reopened, 'new.cs'), 'new'); });
test('stale editors and stale repository instances cannot overwrite updates', async () => { const { repo, api, store } = await fixture(), stale = await VirtualRepository.load(store, api, repo.state.id); const original = await repo.read('view.axaml'); await repo.write('view.axaml', 'new', { expectedOid: original.entry.oid }); await assert.rejects(repo.write('view.axaml', 'lost', { expectedOid: original.entry.oid }), { code: 'stale_file' }); await assert.rejects(stale.write('other', 'x'), { code: 'stale_workspace' }); assert.equal(await read(repo, 'view.axaml'), 'new'); });
test('staging selected hunks checks the diff token', async () => { const a = Array.from({ length: 30 }, (_, i) => `${i}\n`).join(''), { repo } = await fixture({ a }); await repo.write('a', a.replace('1\n', 'one\n').replace('28\n', 'last\n')); const diff = await repo.diff('a'); assert.equal(diff.hunks.length, 2); await repo.stageHunks('a', [0], diff.token); assert.equal(await read(repo, 'a', 'index'), a.replace('1\n', 'one\n')); await assert.rejects(repo.stageHunks('a', [1], diff.token), { code: 'stale_hunk' }); });
test('binary files survive staging, commit and publication', async () => { const { repo, api } = await fixture(); const bytes = Uint8Array.of(0, 255, 1, 2); await repo.write('image.bin', bytes); const diff = await repo.diff('image.bin'); assert.equal(diff.binary, true); await repo.stage(['image.bin']); await repo.commit('binary', author); await repo.push(); const id = repo.state.head.get('image.bin').oid; assert.deepEqual(api.blobs.get(id), bytes); });
test('branch checkout never discards dirty work; stash restores index separately', async () => { const { repo } = await fixture(); await repo.createBranch('feature/x'); await repo.write('view.axaml', 'one'); await repo.stage(['view.axaml']); await repo.write('view.axaml', 'two'); await assert.rejects(repo.checkout('feature/x'), { code: 'dirty_worktree' }); const id = await repo.stash('draft'); await repo.checkout('feature/x'); await repo.applyStash(id, true); assert.equal(await read(repo, 'view.axaml', 'index'), 'one'); assert.equal(await read(repo, 'view.axaml'), 'two'); assert.equal(repo.state.stashes.length, 0); });
test('new offline repository publishes an explicit new branch', async () => { const api = new FakeGitHub(); await api.seed({ seed: 'existing remote' }, { branch: 'bootstrap' }); const store = new MemoryWorkspaceStore(), repo = await VirtualRepository.create(store, api); await repo.setRemote('https://github.com/owner/repo'); await repo.write('hello', 'world'); await repo.stage(['hello']); const id = await repo.commit('initial', author); await assert.rejects(repo.push(), { code: 'non_fast_forward' }); assert.equal(await repo.push({ create: true }), id); assert.equal(api.refs.get('main'), id); });
test('push uploads complete local commit ancestry and never forces', async () => { const { repo, api } = await fixture(); const original = repo.status().head; await repo.write('view.axaml', 'one'); await repo.stage(['view.axaml']); const first = await repo.commit('one', author); await repo.write('view.axaml', 'two'); await repo.stage(['view.axaml']); const second = await repo.commit('two', author); await repo.push(); assert.deepEqual(api.commits.get(second).parents, [first]); assert.deepEqual(api.commits.get(first).parents, [original]); assert.equal(api.refs.get('main'), second); assert.equal(api.calls.find(c => c.method === 'PATCH').body.force, false); });
test('remote divergence rejects push and preserves local commits', async () => { const { repo, api } = await fixture(); const original = repo.status().head; await repo.write('view.axaml', 'local'); await repo.stage(['view.axaml']); const local = await repo.commit('local', author); const remote = await api.seed({ remote: 'new' }, { parents: [original] }); await assert.rejects(repo.push(), { code: 'non_fast_forward' }); assert.equal(repo.status().head, local); assert.equal(api.refs.get('main'), remote); });
for (const when of ['before', 'after']) test(`uncertain push (${when}) journals and reconciles without retry`, async () => { const { repo, api, store } = await fixture(); await repo.write('view.axaml', 'local'); await repo.stage(['view.axaml']); const id = await repo.commit('local', author); api.failRef = when; await assert.rejects(repo.push(), { code: 'push_uncertain' }); assert.ok(repo.state.pendingPush); await assert.rejects(repo.write('other', 'x'), { code: 'pending_push' }); const reopened = await VirtualRepository.load(store, api, repo.state.id); assert.equal(await reopened.reconcilePush(), when === 'after' ? 'published' : 'not-published'); assert.equal(reopened.state.pendingPush, null); assert.equal(api.calls.filter(c => c.method === 'PATCH').length, 1); assert.equal(reopened.status().head, id); });
test('fast-forward pull changes files; dirty pull is rejected', async () => { const { repo, api } = await fixture(); const remote = await api.seed({ 'view.axaml': 'remote\n' }, { parents: [repo.status().head] }); await repo.pull(); assert.equal(repo.status().head, remote); assert.equal(await read(repo, 'view.axaml'), 'remote\n'); await repo.write('view.axaml', 'dirty'); await assert.rejects(repo.pull(), { code: 'dirty_worktree' }); });
test('three-way merge retains conflicts until explicitly resolved', async () => { const { repo } = await fixture({ a: 'base', b: 'base' }); await repo.createBranch('feature'); await repo.write('a', 'ours'); await repo.stage(['a']); const ours = await repo.commit('ours', author); await repo.checkout('feature'); await repo.write('a', 'theirs'); await repo.write('b', 'theirs-only'); await repo.stage(['a', 'b']); const theirs = await repo.commit('theirs', author); await repo.checkout('main'); const result = await repo.merge(theirs); assert.deepEqual(result.conflicts, ['a']); assert.equal(await read(repo, 'b'), 'theirs-only'); await assert.rejects(repo.commit('merge', author), { code: 'merge_conflicts' }); await repo.resolve('a', 'theirs'); const merged = await repo.commit('merge', author); assert.deepEqual(repo.state.commits.get(merged).parents, [ours, theirs]); assert.equal(await read(repo, 'a'), 'theirs'); });
test('abort merge restores original clean worktree', async () => { const { repo } = await fixture({ a: 'base' }); await repo.createBranch('other'); await repo.write('a', 'one'); await repo.stage(['a']); await repo.commit('one', author); await repo.checkout('other'); await repo.write('a', 'two'); await repo.stage(['a']); const other = await repo.commit('two', author); await repo.checkout('main'); await repo.merge(other); await repo.abortMerge('abort'); assert.equal(await read(repo, 'a'), 'one'); assert.equal(repo.status().conflicts.length, 0); });
test('rename, delete, discard and unstage preserve staged state', async () => { const { repo } = await fixture({ a: 'base' }); await repo.rename('a', 'b'); await repo.stage(['a', 'b']); await repo.write('b', 'extra'); await repo.discard(['b'], 'discard'); assert.equal(await read(repo, 'b'), 'base'); await repo.unstage(['a', 'b']); assert.equal(repo.state.index.has('a'), true); assert.equal(repo.state.index.has('b'), false); await assert.rejects(repo.write('b/c', 'collision'), { code: 'path_collision' }); });

test('repeated load-more history calls advance beyond already cached commits', async () => {
    const api = new FakeGitHub(); let parent;
    for (let i = 0; i < 6; i++) parent = await api.seed({ a: `commit ${i}` }, { parents: parent ? [parent] : [] });
    const store = new MemoryWorkspaceStore(), repo = await VirtualRepository.clone(store, api, 'https://github.com/owner/repo');
    assert.equal(repo.state.commits.size, 1);
    assert.equal((await repo.loadHistory(2)).loaded, 2); assert.equal(repo.state.commits.size, 3);
    assert.equal((await repo.loadHistory(2)).loaded, 2); assert.equal(repo.state.commits.size, 5);
    assert.equal((await repo.loadHistory(2)).loaded, 1); assert.equal(repo.state.commits.size, 6);
});
test('virtual edits and hunk staging preserve UTF-8 BOMs', async () => {
    const { repo } = await fixture({ 'bom.txt': '\uFEFFone\r\ntwo\n' });
    assert.equal(await read(repo, 'bom.txt'), '\uFEFFone\r\ntwo\n');
    await repo.write('bom.txt', '\uFEFFone\r\nchanged\n'); const diff = await repo.diff('bom.txt');
    await repo.stageHunks('bom.txt', [0], diff.token);
    assert.equal(await read(repo, 'bom.txt', 'index'), '\uFEFFone\r\nchanged\n');
});

test('empty GitHub repositories fail before object upload and ref journaling', async () => {
    const api = new FakeGitHub(), store = new MemoryWorkspaceStore(), repo = await VirtualRepository.clone(store, api, 'https://github.com/owner/repo');
    await repo.write('hello', 'world'); await repo.stage(['hello']); await repo.commit('first', author);
    await assert.rejects(repo.push({ create: true }), { code: 'empty_remote' });
    assert.equal(repo.state.pendingPush, null); assert.equal(api.calls.filter(call => call.method === 'POST').length, 0);
});
