<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>netstandard2.0</TargetFramework></PropertyGroup><ItemGroup><ProjectReference Include="../XamlG.Syntax/XamlG.Syntax.csproj" /><PackageReference Include="Microsoft.CodeAnalysis.CSharp" /><Compile Include="../Shared/SpanSplitEnumerator.cs" Link="Compatibility/SpanSplitEnumerator.cs" /></ItemGroup></Project>
