<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>netstandard2.0</TargetFramework></PropertyGroup><ItemGroup><PackageReference Include="System.Collections.Immutable" /><Compile Include="../Shared/SpanNumberParser.cs" Link="Compatibility/SpanNumberParser.cs" /><Compile Include="../Shared/SpanSplitEnumerator.cs" Link="Compatibility/SpanSplitEnumerator.cs" /></ItemGroup></Project>
