using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using XamlG.Compiler;
using XamlG.CSharp.Resources;
using XamlG.Roslyn;

namespace XamlG.CSharp.Integration;

internal sealed class LoaderSourceEmitter(CSharpCompilation compilation, XamlProjectCompilation project, XamlLoaderConfiguration configuration)
{
    private readonly StringBuilder _source = new();
    private void Line(string text) => _source.AppendLine(text);
    public string Emit(IReadOnlyList<LoaderCall> calls, CancellationToken cancellationToken)
    {
        Line("// <auto-generated by XamlG: shared loader integration />");
        Line("#nullable enable annotations");
        Line("#nullable disable warnings");
        Line("namespace System.Runtime.CompilerServices {");
        Line("[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        Line("file sealed class InterceptsLocationAttribute : global::System.Attribute { public InterceptsLocationAttribute(int version, string data) { } }");
        Line("}");
        Line("namespace " + XamlCSharpCompilation.InterceptorNamespace + " {");
        Line("file static class LoaderAdapters {");
        for (var i = 0; i < calls.Count; i++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var call = calls[i];
            Line(call.AttributeSource);
            var parameters = string.Join(", ", call.Method.Parameters.Select((p, n) => p.Type.CSharpName() + " __arg" + n));
            Line("public static " + (call.Method.ReturnsVoid ? "void" : call.Method.ReturnType.CSharpName()) + " Call" + i + "(" + parameters + ") {");
            var services = call.HasServices ? "__arg0" : "null";
            var offset = call.HasServices ? 1 : 0;
            if (call.Kind == LoaderCallKind.Uri)
                Line("return LoadUri(" + services + ", __arg" + offset + ", __arg" + (offset + 1) + ");");
            else if (call.StaticTarget is { } target)
                Line(Initializer(target) + "((" + target.Document.ClassSymbol!.CSharpName() + ")__arg" + offset + ", " + services + ");");
            else Line("Populate(__arg" + offset + ", " + services + ");");
            Line("}");
        }
        if (calls.Any(c => c.Kind == LoaderCallKind.Object && c.StaticTarget == null)) EmitObjectDispatch();
        if (calls.Any(c => c.Kind == LoaderCallKind.Uri)) EmitUriDispatch();
        Line("}"); Line("}");
        return _source.ToString();
    }
    private void EmitObjectDispatch()
    {
        Line("private static void Populate(object instance, global::System.IServiceProvider? services) {");
        Line("if (instance is null) throw new global::System.ArgumentNullException(nameof(instance));");
        var compiled = project.Documents.Where(d => d.Output.Success && !d.Document.IsSkipped && d.Document.ClassSymbol != null && d.Document.Options.GenerateInitializeComponent &&
            XamlLoaderAdapterCompiler.CanReference(compilation, d.Document.ClassSymbol)).ToArray();
        var original = OriginalLoader(uri: false);
        var compiledTypes = new HashSet<ITypeSymbol>(compiled.Select(d => d.Document.ClassSymbol!), SymbolEqualityComparer.Default);
        var skipped = project.Documents.Where(d => d.Document.IsSkipped && d.Document.ClassSymbol != null &&
            !compiledTypes.Contains(d.Document.ClassSymbol)).ToArray();
        // The most specific declaration wins even when an opted-out component and a
        // compiled component inherit from one another.
        var targets = compiled.Concat(original == null ? Enumerable.Empty<XamlProjectDocumentResult>() : skipped)
            .OrderByDescending(d => Depth(d.Document.ClassSymbol!));
        var index = 0;
        foreach (var target in targets)
        {
            if (target.Document.IsSkipped)
            {
                var type = target.Document.ClassSymbol!;
                Line("if (IsInstanceOf(instance, " + CSharpNames.Literal(type.MetadataName()) + ", " + CSharpNames.Literal(type.ContainingAssembly.Identity.Name) +
                    ")) { " + OriginalCall(original!, "instance") + "; return; }");
                continue;
            }
            var variable = "__root" + index++;
            Line("if (instance is " + target.Document.ClassSymbol!.CSharpName() + " " + variable + ") { " + Initializer(target) + "(" + variable + ", services); return; }");
        }
        Line("throw new global::System.InvalidOperationException(\"No compiled XamlG component initializer matches \" + instance.GetType().FullName);");
        Line("}");
        if (original != null && skipped.Any())
        {
            Line("private static bool IsInstanceOf(object instance, string name, string assembly) {");
            Line("for (var type = instance.GetType(); type != null; type = type.BaseType) {");
            Line("var definition = type.IsGenericType ? type.GetGenericTypeDefinition() : type;");
            Line("if (definition.FullName == name && definition.Assembly.GetName().Name == assembly) return true;");
            Line("}");
            Line("return false;");
            Line("}");
        }
    }
    private void EmitUriDispatch()
    {
        Line("private static object LoadUri(global::System.IServiceProvider? services, global::System.Uri uri, global::System.Uri? baseUri) {");
        Line("var absolute = global::XamlG.Runtime.XamlCompiledResourceAddress.Absolute(uri, baseUri);");
        Line("var key = global::XamlG.Runtime.XamlCompiledResourceAddress.Key(absolute);");
        Line("switch (key) {");
        var documentsByUri = new Dictionary<string, XamlProjectDocumentResult>(StringComparer.Ordinal);
        foreach (var document in project.Documents)
            if (document.ResourceUri is { } uri && !documentsByUri.ContainsKey(uri)) documentsByUri.Add(uri, document);
        var resourceGroups = project.Resources.Resources.GroupBy(r => r.Uri, StringComparer.Ordinal).OrderBy(g => g.Key, StringComparer.Ordinal).ToArray();
        var exportedUris = new HashSet<string>(resourceGroups.Select(group => group.Key), StringComparer.Ordinal);
        foreach (var group in resourceGroups)
        {
            if (group.Count() != 1) continue;
            var resource = group.Single();
            string? factory = null;
            if (resource.ExternalFactory is { } external)
                factory = external.ContainingType.CSharpName() + "." + CSharpNames.Method(external);
            else
            {
                documentsByUri.TryGetValue(resource.Uri, out var document);
                if (document?.Output.Success == true && document.Output.BuildMethodName != null &&
                    (document.Document.ClassSymbol == null || XamlLoaderAdapterCompiler.CanReference(compilation, document.Document.ClassSymbol)))
                    factory = Factory(document) + "." + document.Output.BuildMethodName;
            }
            if (factory != null)
                Line("case " + CSharpNames.Literal(resource.Uri) + ": return " + factory + "(global::XamlG.Runtime.XamlResourceServices.Enter(services ?? EmptyServices.Instance, key));");
        }
        var optedOutLoader = OriginalLoader(uri: true);
        if (optedOutLoader != null)
            foreach (var uri in project.Documents.Where(document => document.Document.IsSkipped && document.ResourceUri != null &&
                !exportedUris.Contains(document.ResourceUri)).Select(document => document.ResourceUri!).Distinct(StringComparer.Ordinal))
                Line("case " + CSharpNames.Literal(uri) + ": return " + OriginalCall(optedOutLoader, "absolute, null") + ";");
        Line("}");
        // Existing referenced binaries already contain compiled code. Preserve their official
        // loader path only when that compiled index is visible in reference metadata. Never
        // delegate a local/unknown URI to a runtime XAML compiler.
        var original = compilation.GetTypeByMetadataName(configuration.TypeMetadataName)?.GetMembers(configuration.MethodName).OfType<IMethodSymbol>()
            .FirstOrDefault(m => m.IsStatic && m.Parameters.Length == 3 && m.Parameters[0].Type.HasMetadataName("System.IServiceProvider") &&
                m.Parameters[1].Type.HasMetadataName("System.Uri") && m.Parameters[2].Type.HasMetadataName("System.Uri"));
        if (original != null && configuration.LegacyIndexMetadataName != null)
        {
            var assemblies = compilation.SourceModule.ReferencedAssemblySymbols.Where(a => a.GetTypeByMetadataName(configuration.LegacyIndexMetadataName) != null)
                .Select(a => a.Identity.Name.ToLowerInvariant()).Distinct(StringComparer.Ordinal).OrderBy(a => a, StringComparer.Ordinal).ToArray();
            if (assemblies.Length != 0)
            {
                Line("if (absolute.Scheme == " + CSharpNames.Literal(project.Documents.FirstOrDefault()?.Document.Options.ResourceUri is { } uri ? new Uri(uri).Scheme : "avares") + ") {");
                Line("switch (absolute.Host.ToLowerInvariant()) {");
                foreach (var assembly in assemblies) Line("case " + CSharpNames.Literal(assembly) + ":");
                Line("return " + original.ContainingType.CSharpName() + "." + CSharpNames.Method(original) + "(services, absolute, null);");
                Line("}"); Line("}");
            }
        }
        Line("throw new global::System.InvalidOperationException(\"No compiled resource is available at \" + key);");
        Line("}");
        Line("private sealed class EmptyServices : global::System.IServiceProvider { internal static readonly EmptyServices Instance = new EmptyServices(); public object? GetService(global::System.Type type) => null; }");
    }
    private IMethodSymbol? OriginalLoader(bool uri) => compilation.GetTypeByMetadataName(configuration.TypeMetadataName)?
        .GetMembers(configuration.MethodName).OfType<IMethodSymbol>()
        .Where(method => method.IsStatic && !method.IsGenericMethod && method.Parameters.All(parameter => parameter.RefKind == RefKind.None))
        .Where(method => uri
            ? method.ReturnType.SpecialType == SpecialType.System_Object && method.Parameters.Length is 2 or 3 &&
                method.Parameters[method.Parameters.Length - 2].Type.HasMetadataName("System.Uri") && method.Parameters.Last().Type.HasMetadataName("System.Uri") &&
                (method.Parameters.Length == 2 || method.Parameters[0].Type.HasMetadataName("System.IServiceProvider"))
            : method.ReturnsVoid && method.Parameters.Length is 1 or 2 && method.Parameters.Last().Type.SpecialType == SpecialType.System_Object &&
                (method.Parameters.Length == 1 || method.Parameters[0].Type.HasMetadataName("System.IServiceProvider")))
        .OrderByDescending(method => method.Parameters.Length).FirstOrDefault();
    private static string OriginalCall(IMethodSymbol method, string arguments) => method.ContainingType.CSharpName() + "." + CSharpNames.Method(method) + "(" +
        (method.Parameters[0].Type.HasMetadataName("System.IServiceProvider") ? "services, " : string.Empty) + arguments + ")";
    private static string Factory(XamlProjectDocumentResult document) =>
        document.Document.ClassSymbol != null && document.Document.CanAugmentClass
            ? document.Document.ClassSymbol.CSharpName() : "global::" + document.Output.FactoryTypeName;
    internal static string Initializer(XamlProjectDocumentResult document) => Factory(document) + "." +
        ComponentInitializationEmitter.Method(document.Document.Options.DocumentId ?? document.Input.Syntax.Path);
    private static int Depth(INamedTypeSymbol type)
    {
        var depth = 0;
        for (var current = type.BaseType; current != null; current = current.BaseType) depth++;
        return depth;
    }
}
