using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using XamlG.Compiler;
using XamlG.CSharp.Resources;
using XamlG.Roslyn;

namespace XamlG.CSharp.Integration;

internal sealed class LoaderSourceEmitter(CSharpCompilation compilation, XamlProjectCompilation project, XamlLoaderConfiguration configuration)
{
    private readonly StringBuilder _source = new();
    private void Line(string text) => _source.AppendLine(text);
    public string Emit(IReadOnlyList<LoaderCall> calls, CancellationToken cancellationToken)
    {
        Line("// <auto-generated by XamlG: shared loader integration />");
        Line("#nullable enable annotations");
        Line("#nullable disable warnings");
        Line("namespace System.Runtime.CompilerServices {");
        Line("[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        Line("file sealed class InterceptsLocationAttribute : global::System.Attribute { public InterceptsLocationAttribute(int version, string data) { } }");
        Line("}");
        Line("namespace " + XamlCSharpCompilation.InterceptorNamespace + " {");
        Line("file static class LoaderAdapters {");
        for (var i = 0; i < calls.Count; i++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var call = calls[i];
            Line(call.AttributeSource);
            var parameters = string.Join(", ", call.Method.Parameters.Select((p, n) => p.Type.CSharpName() + " __arg" + n));
            Line("public static " + (call.Method.ReturnsVoid ? "void" : call.Method.ReturnType.CSharpName()) + " Call" + i + "(" + parameters + ") {");
            var services = call.HasServices ? "__arg0" : "null";
            var offset = call.HasServices ? 1 : 0;
            if (call.Kind == LoaderCallKind.Uri)
                Line("return LoadUri(" + services + ", __arg" + offset + ", __arg" + (offset + 1) + ");");
            else if (call.StaticTarget is { } target)
                Line(Initializer(target) + "((" + target.Document.ClassSymbol!.CSharpName() + ")__arg" + offset + ", " + services + ");");
            else Line("Populate(__arg" + offset + ", " + services + ");");
            Line("}");
        }
        if (calls.Any(c => c.Kind == LoaderCallKind.Object && c.StaticTarget == null)) EmitObjectDispatch();
        if (calls.Any(c => c.Kind == LoaderCallKind.Uri)) EmitUriDispatch();
        Line("}"); Line("}");
        return _source.ToString();
    }
    private void EmitObjectDispatch()
    {
        Line("private static void Populate(object instance, global::System.IServiceProvider? services) {");
        Line("if (instance is null) throw new global::System.ArgumentNullException(nameof(instance));");
        var targets = project.Documents.Where(d => d.Output.Success && d.Document.ClassSymbol != null && d.Document.Options.GenerateInitializeComponent &&
            XamlLoaderAdapterCompiler.CanReference(compilation, d.Document.ClassSymbol)).OrderByDescending(d => Depth(d.Document.ClassSymbol!));
        var index = 0;
        foreach (var target in targets)
        {
            var variable = "__root" + index++;
            Line("if (instance is " + target.Document.ClassSymbol!.CSharpName() + " " + variable + ") { " + Initializer(target) + "(" + variable + ", services); return; }");
        }
        Line("throw new global::System.InvalidOperationException(\"No compiled XamlG component initializer matches \" + instance.GetType().FullName);");
        Line("}");
    }
    private void EmitUriDispatch()
    {
        Line("private static object LoadUri(global::System.IServiceProvider? services, global::System.Uri uri, global::System.Uri? baseUri) {");
        Line("var absolute = global::XamlG.Runtime.XamlCompiledResourceAddress.Absolute(uri, baseUri);");
        Line("var key = global::XamlG.Runtime.XamlCompiledResourceAddress.Key(absolute);");
        Line("switch (key) {");
        foreach (var group in project.Resources.Resources.GroupBy(r => r.Uri, StringComparer.Ordinal).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            if (group.Count() != 1) continue;
            var resource = group.Single();
            string? factory = null;
            if (resource.ExternalFactory is { } external)
                factory = external.ContainingType.CSharpName() + "." + CSharpNames.Method(external);
            else
            {
                var document = project.Documents.FirstOrDefault(d => d.ResourceUri == resource.Uri);
                if (document?.Output.Success == true && document.Output.BuildMethodName != null &&
                    (document.Document.ClassSymbol == null || XamlLoaderAdapterCompiler.CanReference(compilation, document.Document.ClassSymbol)))
                    factory = (document.Document.ClassSymbol?.CSharpName() ?? "global::" + document.Output.FactoryTypeName) + "." + document.Output.BuildMethodName;
            }
            if (factory != null)
                Line("case " + CSharpNames.Literal(resource.Uri) + ": return " + factory + "(global::XamlG.Runtime.XamlResourceServices.Enter(services ?? EmptyServices.Instance, key));");
        }
        Line("}");
        // Existing referenced binaries already contain compiled code. Preserve their official
        // loader path only when that compiled index is visible in reference metadata. Never
        // delegate a local/unknown URI to a runtime XAML compiler.
        var original = compilation.GetTypeByMetadataName(configuration.TypeMetadataName)?.GetMembers(configuration.MethodName).OfType<IMethodSymbol>()
            .FirstOrDefault(m => m.IsStatic && m.Parameters.Length == 3 && m.Parameters[0].Type.HasMetadataName("System.IServiceProvider") &&
                m.Parameters[1].Type.HasMetadataName("System.Uri") && m.Parameters[2].Type.HasMetadataName("System.Uri"));
        if (original != null && configuration.LegacyIndexMetadataName != null)
        {
            var assemblies = compilation.SourceModule.ReferencedAssemblySymbols.Where(a => a.GetTypeByMetadataName(configuration.LegacyIndexMetadataName) != null)
                .Select(a => a.Identity.Name.ToLowerInvariant()).Distinct(StringComparer.Ordinal).OrderBy(a => a, StringComparer.Ordinal).ToArray();
            if (assemblies.Length != 0)
            {
                Line("if (absolute.Scheme == " + CSharpNames.Literal(project.Documents.FirstOrDefault()?.Document.Options.ResourceUri is { } uri ? new Uri(uri).Scheme : "avares") + ") {");
                Line("switch (absolute.Host.ToLowerInvariant()) {");
                foreach (var assembly in assemblies) Line("case " + CSharpNames.Literal(assembly) + ":");
                Line("return " + original.ContainingType.CSharpName() + "." + CSharpNames.Method(original) + "(services, absolute, null);");
                Line("}"); Line("}");
            }
        }
        Line("throw new global::System.InvalidOperationException(\"No compiled resource is available at \" + key);");
        Line("}");
        Line("private sealed class EmptyServices : global::System.IServiceProvider { internal static readonly EmptyServices Instance = new EmptyServices(); public object? GetService(global::System.Type type) => null; }");
    }
    internal static string Initializer(XamlProjectDocumentResult document) => document.Document.ClassSymbol!.CSharpName() + "." +
        ComponentInitializationEmitter.Method(document.Document.Options.DocumentId ?? document.Input.Syntax.Path);
    private static int Depth(INamedTypeSymbol type)
    {
        var depth = 0;
        for (var current = type.BaseType; current != null; current = current.BaseType) depth++;
        return depth;
    }
}
