using System.Collections.Immutable;
using System.Threading;
using Microsoft.CodeAnalysis;
using XamlG.Compiler;
using XamlG.CSharp.Resources;
using XamlG.Roslyn;

namespace XamlG.CSharp;

/// <summary>Deterministically lowers bound operations to statically typed C#. Generated code never reparses XAML.</summary>
public sealed class CSharpEmitter
{
    public XamlEmissionResult Emit(BoundDocument document, CancellationToken cancellationToken = default)
    {
        var context = new EmissionContext(document, cancellationToken);
        var writer = context.Writer;
        var typeName = document.ClassSymbol?.ToDisplayString() ?? document.Options.GeneratedNamespace + ".Document_" + context.Id;
        var classFactory = document.ClassSymbol != null && XamlClassFactory.CanCreate(document.ClassSymbol, document.Options, document.Syntax.Root);
        var build = classFactory ? XamlClassFactory.Method(document.Options.DocumentId ?? document.Syntax.Path) :
            document.ClassSymbol == null && document.Options.GenerateBuildMethod ? "Build" : null;
        var populate = "__XamlGPopulate_" + context.Id;
        if (!document.Success)
            return new(context.Id + ".xaml.g.cs", string.Empty, typeName, build, populate,
                context.Diagnostics.ToImmutableArray(), ImmutableArray<XamlSourceMapping>.Empty) { FactoryMetadataName = document.ClassSymbol?.MetadataName() ?? typeName };
        writer.Line("// <auto-generated by XamlG />");
        writer.Line("#nullable enable annotations");
        writer.Line("#nullable disable warnings");
        var root = document.Root!;
        var namespaceName = document.ClassSymbol?.ContainingNamespace is { IsGlobalNamespace: false } ns
            ? ns.ToDisplayString() : document.ClassSymbol == null ? document.Options.GeneratedNamespace : string.Empty;
        if (namespaceName.Length != 0) writer.Open("namespace " + namespaceName);
        var containers = new Stack<INamedTypeSymbol>();
        for (var type = document.ClassSymbol; type != null; type = type.ContainingType) containers.Push(type);
        var nesting = containers.Count;
        if (containers.Count == 0)
        {
            var accessibility = root.Type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
            writer.Open(accessibility + " static class Document_" + context.Id);
        }
        else
        {
            foreach (var type in containers)
            {
                var kind = type.IsRecord ? type.IsValueType ? "record struct " : "record class " : type.IsValueType ? "struct " : "class ";
                var parameters = type.Arity == 0 ? string.Empty : "<" + string.Join(", ", type.TypeParameters.Select(p => CSharpNames.Identifier(p.Name))) + ">";
                writer.Open("partial " + kind + CSharpNames.Identifier(type.Name) + parameters);
            }
        }
        var flow = new ObjectEmitter(context);
        if (document.ClassSymbol != null && document.Options.GenerateNamedFields)
            foreach (var named in BoundTraversal.Objects(root).Where(n => n.Name != null && n.NameScopeId == root.NameScopeId))
                if (!document.ClassSymbol.GetMembers(named.Name!).Any())
                    writer.Line(named.FieldModifier + " " + named.Type.CSharpName() + " " + CSharpNames.Identifier(named.Name!) + " = default!;");
        if (classFactory)
        {
            if (document.ClassSymbol!.GetMembers(build!).Any()) context.Error("The code-behind class defines a reserved generated factory method.", root.Syntax.NameSpan);
            else ClassFactoryEmitter.Emit(context, root.Type.CSharpName(), build!);
        }
        else if (build != null)
        {
            writer.Open("public static " + root.Type.CSharpName() + " Build(" + CSharpNames.Provider + "? __services = null)");
            flow.EmitContext("__context", "__services", "null");
            writer.Open("try");
            var value = flow.Emit(root, "__context", null, null);
            flow.Complete("__context", value);
            writer.Line("return " + value + ";");
            writer.Close(); ConstructionFailureEmitter.Emit(context, "__context"); writer.Close();
        }
        writer.Open("public static void " + populate + "(" + root.Type.CSharpName() + " __root, " + CSharpNames.Provider + "? __services = null)");
        if (root.Type.IsReferenceType) writer.Line("if (__root is null) throw new global::System.ArgumentNullException(nameof(__root));");
        flow.EmitContext("__context", "__services", "__root");
        writer.Open("try");
        flow.Emit(root, "__context", "__root", null);
        flow.Complete("__context", "__root");
        writer.Close(); ConstructionFailureEmitter.Emit(context, "__context"); writer.Close();
        if (document.ClassSymbol != null && document.Options.GenerateInitializeComponent)
            ComponentInitializationEmitter.Emit(context, populate);
        flow.EmitNamespaceMaps();
        new ServiceContractEmitter(context).Emit();
        context.DynamicSetters.Emit(); context.EmitMetadataHelpers();
        if (nesting == 0) writer.Close(); else for (var i = 0; i < nesting; i++) writer.Close();
        if (namespaceName.Length != 0) writer.Close();
        return new(context.Id + ".xaml.g.cs", writer.ToString(), typeName, build, populate,
            context.Diagnostics.ToImmutableArray(), context.Mappings.ToImmutableArray()) { FactoryMetadataName = document.ClassSymbol?.MetadataName() ?? typeName };
    }
}
