using System.Collections.Immutable;
using System.Threading;
using Microsoft.CodeAnalysis;
using XamlG.Compiler;
using XamlG.CSharp.Resources;
using XamlG.Roslyn;

namespace XamlG.CSharp;

/// <summary>Deterministically lowers bound operations to statically typed C#. Generated code never reparses XAML.</summary>
public sealed class CSharpEmitter
{
    public XamlEmissionResult Emit(BoundDocument document, CancellationToken cancellationToken = default)
        => Emit(document, cancellationToken, shareServices: false);

    internal XamlEmissionResult Emit(BoundDocument document, CancellationToken cancellationToken, bool shareServices)
    {
        using var context = new EmissionContext(document, cancellationToken);
        if (document.IsSkipped)
            return new(context.Id + ".xaml.g.cs", string.Empty, string.Empty, null, string.Empty,
                context.Diagnostics.ToImmutableArray(), ImmutableArray<XamlSourceMapping>.Empty) { IsSkipped = true };
        var writer = context.Writer;
        var augment = document.ClassSymbol != null && document.CanAugmentClass;
        var typeName = augment ? document.ClassSymbol!.ToDisplayString() : document.Options.GeneratedNamespace + ".Document_" + context.Id;
        var metadataName = augment ? document.ClassSymbol!.MetadataName() : typeName;
        var classFactory = document.ClassSymbol != null && XamlClassFactory.CanCreate(document.ClassSymbol, document.Options, document.Syntax.Root);
        var build = classFactory ? augment ? XamlClassFactory.Method(document.Options.DocumentId ?? document.Syntax.Path) : "Build" :
            document.ClassSymbol == null && document.Options.GenerateBuildMethod ? "Build" : null;
        var populate = "__XamlGPopulate_" + context.Id;
        if (!document.Success)
            return new(context.Id + ".xaml.g.cs", string.Empty, typeName, build, populate,
                context.Diagnostics.ToImmutableArray(), ImmutableArray<XamlSourceMapping>.Empty) { FactoryMetadataName = metadataName };
        if (shareServices && document.Runtime.Services.Length != 0 && document.ClassSymbol?.IsGenericType != true)
            context.SharedServices = new ServiceContractEmitter(context).CreateShared();
        writer.Line("// <auto-generated by XamlG />");
        writer.Line("#nullable enable annotations");
        writer.Line("#nullable disable warnings");
        var root = document.Root!;
        var namespaceName = augment ? document.ClassSymbol!.ContainingNamespace is { IsGlobalNamespace: false } ns
            ? ns.ToDisplayString() : string.Empty : document.Options.GeneratedNamespace;
        if (namespaceName.Length != 0) writer.Open("namespace " + namespaceName);
        var containers = new Stack<INamedTypeSymbol>();
        for (var type = augment ? document.ClassSymbol : null; type != null; type = type.ContainingType) containers.Push(type);
        var nesting = containers.Count;
        if (containers.Count == 0)
        {
            var accessibility = root.Type.DeclaredAccessibility == Accessibility.Public && document.ClassModifier == "public" ? "public" : "internal";
            writer.Open(accessibility + " static class Document_" + context.Id);
        }
        else
        {
            foreach (var type in containers)
            {
                var kind = type.IsRecord ? type.IsValueType ? "record struct " : "record class " : type.IsValueType ? "struct " : "class ";
                var parameters = type.Arity == 0 ? string.Empty : "<" + string.Join(", ", type.TypeParameters.Select(p => CSharpNames.Identifier(p.Name))) + ">";
                writer.Open("partial " + kind + CSharpNames.Identifier(type.Name) + parameters);
            }
        }
        var flow = new ObjectEmitter(context);
        // Classless resources expose both Build and Populate. Share their graph body so
        // Roslyn only binds, analyzes and compiles each template and property assignment once.
        var sharePopulation = !classFactory && build != null && root.Type.IsReferenceType;
        var populateCore = "__XamlGPopulateCore_" + context.Id;
        if (augment && document.Options.GenerateNamedFields)
            foreach (var field in context.NamedFields)
                if (!document.ClassSymbol!.GetMembers(field.Name).Any())
                    writer.Line(field.Object.FieldModifier + " " + field.Object.Type.CSharpName() + " " + CSharpNames.Identifier(field.Name) + " = default!;");
        if (classFactory)
        {
            if (augment && document.ClassSymbol!.GetMembers(build!).Any()) context.Error("The code-behind class defines a reserved generated factory method.", root.Syntax.NameSpan);
            else ClassFactoryEmitter.Emit(context, root.Type.CSharpName(), build!);
        }
        else if (build != null)
        {
            writer.Open("public static " + root.Type.CSharpName() + " Build(" + CSharpNames.Provider + "? __services = null)");
            flow.EmitContext("__context", "__services", "null");
            writer.Open("try");
            var value = sharePopulation ? flow.ConstructRoot(root, "__context") : flow.Emit(root, "__context", null, null);
            if (sharePopulation) writer.Line(populateCore + "(" + value + ", __context);");
            flow.Complete("__context", value);
            writer.Line("return " + value + ";");
            writer.Close(); ConstructionFailureEmitter.Emit(context, "__context"); writer.Close();
        }
        writer.Open("public static void " + populate + "(" + root.Type.CSharpName() + " __root, " + CSharpNames.Provider + "? __services = null)");
        if (root.Type.IsReferenceType) writer.Line("if (__root is null) throw new global::System.ArgumentNullException(nameof(__root));");
        flow.EmitContext("__context", "__services", "__root");
        writer.Open("try");
        if (sharePopulation) writer.Line(populateCore + "(__root, __context);");
        else flow.Emit(root, "__context", "__root", null);
        flow.Complete("__context", "__root");
        writer.Close(); ConstructionFailureEmitter.Emit(context, "__context"); writer.Close();
        if (sharePopulation)
        {
            writer.Open("private static void " + populateCore + "(" + root.Type.CSharpName() + " __root, " + CSharpNames.Context + " __context)");
            flow.Emit(root, "__context", "__root", null);
            writer.Close();
        }
        if (document.ClassSymbol != null && document.Options.GenerateInitializeComponent)
            ComponentInitializationEmitter.Emit(context, populate);
        flow.EmitContextHelpers(); flow.EmitNamespaceMaps();
        new ServiceContractEmitter(context).Emit();
        context.DynamicSetters.Emit(); context.DynamicAdds.Emit(); context.EmitMetadataHelpers();
        if (nesting == 0) writer.Close(); else for (var i = 0; i < nesting; i++) writer.Close();
        if (namespaceName.Length != 0) writer.Close();
        return new(context.Id + ".xaml.g.cs", writer.ToString(), typeName, build, populate,
            context.Diagnostics.ToImmutableArray(), context.Mappings.ToImmutableArray())
            { FactoryMetadataName = metadataName, SharedServices = context.SharedServices };
    }
}
