<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseMicroCom>true</UseMicroCom>
    <ApplicationIcon>$(SharedAssetsPath)\icon.ico</ApplicationIcon>
  </PropertyGroup>


  <ItemGroup>
    <Content Include="NativeControls\Gtk\nodes.mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(ControlCatalogAvaloniaRoot)/src\Avalonia.Wayland\Avalonia.Wayland.csproj" />
    <ProjectReference Include="$(ControlCatalogAvaloniaRoot)/src\Headless\Avalonia.Headless.Vnc\Avalonia.Headless.Vnc.csproj" />
    <ProjectReference Include="$(ControlCatalogAvaloniaRoot)/src\Avalonia.Dialogs\Avalonia.Dialogs.csproj" />
    <ProjectReference Include="$(ControlCatalogAvaloniaRoot)/src\Linux\Avalonia.LinuxFramebuffer\Avalonia.LinuxFramebuffer.csproj" />
    <ProjectReference Include="..\ControlCatalog\ControlCatalog.csproj" />
    <ProjectReference Include="$(ControlCatalogAvaloniaRoot)/src\Avalonia.X11\Avalonia.X11.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <!-- For Microsoft.CodeAnalysis -->
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <Import Project="$(ControlCatalogAvaloniaRoot)/build\BuildTargets.targets" />
  <Import Project="$(ControlCatalogAvaloniaRoot)/build\SampleApp.props" />
  <Import Project="$(ControlCatalogAvaloniaRoot)/build\ReferenceCoreLibraries.props" />
  <Import Project="$(ControlCatalogAvaloniaRoot)/build\MicroCOM.props" />
</Project>
